name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Linux Build (Clang Debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip clang cmake
          python3 -m venv .venv
          source .venv/bin/activate
          pip install conan

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.*') }}

      - name: Build project (clang-debug)
        run: |
          chmod +x ./build.sh
          ./build.sh clang-debug

  build-macos:
    name: macOS Build (Clang Debug)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install python3 cmake llvm
          python3 -m venv .venv
          source .venv/bin/activate
          pip install conan

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.*') }}

      - name: Build project (clang-debug)
        run: |
          chmod +x ./build.sh
          ./build.sh clang-debug

  build-windows:
    name: Windows Build (Clang Debug)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          choco install llvm cmake python --pre
          python -m venv .venv
          source .venv/Scripts/activate
          pip install conan

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.*') }}

      - name: Build project (clang-debug)
        shell: bash
        run: |
          chmod +x ./build.sh
          ./build.sh clang-debug

